server:
  port: 8080

spring:
  profiles:
    active: local  # 🎯 기본값: 로컬 환경 (H2 사용)

  # 🗄️ 기본 데이터소스 설정 (profile이 활성화 안 됐을 때 fallback)
  datasource:
    url: jdbc:h2:mem:callog_default
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

# 🔐 JWT 설정 (모든 환경 공통)
jwt:
  secret: mySecretKeyForCallogUserApplicationThisShouldBeLongEnoughForSecurity123456789
  expiration: 86400000  # 24시간

# 📝 로깅 기본 설정
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'