spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/callog_user?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: callog
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      maximum-pool-size: 10  # 추가: 커넥션 풀 크기 설정

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # ✅ MySQL Dialect로 변경!
    hibernate:
      ddl-auto: create-drop  # ✅ create-drop / update (데이터 유지)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC  # 타임존 설정 추가

# 🔐 JWT 로컬 설정
jwt:
  secret: localDevelopmentSecretKeyForTestingOnly123456789
  expiration: 86400000

# 📝 로컬 로깅 설정
logging:
  level:
    com.callog.callog_user: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG  # 추가: DB 커넥션 풀 로그

server:
  port: 8082