server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/callog_user?serverTimezone=UTC&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: callog
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false

# JWT 설정 추가! 🔐
jwt:
  secret: mySecretKeyForCallogUserApplicationThisShouldBeLongEnoughForSecurity123456789
  # 비밀키는 실제로는 환경변수나 별도 설정파일로 관리해야 해! 지금은 테스트용
  expiration: 86400000  # 24시간 (밀리초 단위: 24 * 60 * 60 * 1000)

